### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by yannick-cw** [yannick-cw/notionfy#1]
If there is demand for it I could look into publishing for windows

**Comment by holosen** [comment]
I would be very interested in this.

**Comment by ajstont** [comment]
I just saw the Reddit post (linked below) on syncing kindle highlights to Notion. I won't lie, it made me feel all giddy.  

I don't know what GitHub is (pardon my ignorance), but I just created an account for the sole purpose of requesting this feature.

Iv'e also reached out on twitter to see if I can drum up any support.

Needless to say. I'm overly enthusiastic for this feature to receive windows support!

Let me know if I can help in any way.

Kind regards

Alex   

https://www.reddit.com/r/NotionSo/comments/e9sruu/would_anyone_using_windows_have_interest_in/
![image](https://user-images.githubusercontent.com/58830063/70751466-37f25500-1d7c-11ea-8e57-4fb4e6c34e28.png)

![image](https://user-images.githubusercontent.com/58830063/70758718-95dc6800-1d8f-11ea-8386-333b421be626.png)

**Comment by yannick-cw** [comment]
Okay this look like a lot of support for getting it working on windows, I'll do it :)

**Comment by yannick-cw** [comment]
Building on windows works fine... But parsing the kindle file currently fails with:
```
ParsErr "(line 1, column 34):\nunexpected \"\\n\"\nexpecting \"\\r\\n\" or \"==========\\r\\n\""Access violation in generated code when reading 0000000094cdeebe
```
Need to investigate whats going on there

**Comment by yannick-cw** [comment]
@holosen @ajstont can you give it a try?
I added a win release zip (https://github.com/yannick-cw/notionfy/releases/download/0.1/notionfy_win.zip)

1. Download the zip file to .e.g `Downloads`
2. Right click extract all (to suggested folder)
3. open power shell
4. `cd .\Downloads\notionfy_win\`
5. `.\notionfy.exe`

Should give you the outcome
```
Usage: .....
```

That means it works so far.
Now run it with your configuration:

```
.\notionfy.exe --token "TOKEN_HERE" --page "PAGE_ID_HERE" --kindle "D:"
```

Where token is token form the cookie and page id from the url of the page you want to add the snippets. When I connect my kindle to a windows machine it is mounted as `D:` so check under what path you kindle is mounted and add that instead of `:D`

Let me know if it works out

**Comment by holosen** [comment]
It is currently still syncing my Highlights, so it seems to be working! Amazing.

**Comment by yannick-cw** [comment]
Great! Please let me know if anything does not work or what could be improved

**Comment by crispycaspr** [comment]
Hi, thanks for this! Super excited that you're supporting this on Windows. Unfortunately, I tried this out but I'm getting this error and I'm not sure if I'm doing something wrong:
`ParsErr "(line 3364, column 180):\nunexpected \" \"\nexpecting \"==========\\n\""`

I'm pretty sure my token value, page ID, and Kindle drive are correct. Is there an issue with MyClippings maybe? Appreciate your input and work on this. This is also my first time commenting on Git so let me know if I should be posting elsewhere.

**Comment by yannick-cw** [comment]
Hey @airsylph, thanks for reporting! I moved your problem to #3 so we can discuss it in a new issue
