### ISSUE TITLE
Path to kindle on Windows need double backslash

### ISSUE THREAD

**Issue by twkrol** [yannick-cw/notionfy#10]
Path to kindle on Windows need to be in form 
`"D:\\" `
instead of typical
`"D:" or "D:\"`
Today I've lost time and tried many times until found it. Please add info to manual or modify codebase to help Windows users mitigate this.
Thanks

**Comment by yannick-cw** [comment]
Thanks for reporting, I'll fix this. Unfortunately I do not use it on windows so have not noticed that.

**Comment by yannick-cw** [comment]
f44d55d99c8fa815cb0d4bce0913a59338f42cb4 should clarify.
I think just writing `"D:/"` instead of the backslashes work (Does for me in bootcamp). Double backslash were needed as I think otherwise the `"` was escaped and everything went wrong :)
Could you try with `"D:/"`
