### ISSUE TITLE
UnsupportedFeatureError

### ISSUE THREAD

**Issue by sudohainguyen** [yannick-cw/notionfy#12]
I'm encountering a problem when trying to sync for the first time. An exception came up with a message as below

> "Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/150595542.invoke_MT(Object, Object)"

I'm using Ubuntu 20.04 OS and I already make it executable using chmod.

**Comment by yannick-cw** [comment]
Thanks for reporting, maybe you are the first Linux user :) I'll have a look

**Comment by yannick-cw** [comment]
I updated some version, maybe you can try this release: https://github.com/yannick-cw/notionfy/releases/tag/0.2.3

I am not very confident this works, but if it might save me a lot of work, otherwise I'll have to dig a bit :)

**Comment by sudohainguyen** [comment]
Seems like the problem is still unsolved, but keep working! I really appreciate this project :)

**Comment by yannick-cw** [comment]
This seems to be due to: https://github.com/oracle/graal/issues/2214

Looking for a fix

**Comment by yannick-cw** [comment]
Could you try out 0.2.5
https://github.com/yannick-cw/notionfy/releases/tag/0.2.5?

**Comment by sudohainguyen** [comment]
Thanks a lot! Seems like it works smoothly in version 0.2.5
