### ISSUE TITLE
Syncing lead to 4xx for big clippings file

### ISSUE THREAD

**Issue by yannick-cw** [yannick-cw/notionfy#13]
Hi @yannick-cw,
[output.txt](https://github.com/yannick-cw/notionfy/files/5125497/output.txt)

I attach a file with the last part of my output
The output is so long that the command window doesn't let me browse up
Btw, I'm using windows 10
Thank you so much

_Originally posted by @sgomezp in https://github.com/yannick-cw/notionfy/issues/11#issuecomment-680181680_

**Comment by sgomezp** [comment]
Hi @yannick-cw 
I'm using the latest version (0.2.4). Now, I have some highlights in my Notion page but no all of them.
In the attached file `"last_output.txt" ` you would see the error output.
I'm also attached a copy of my notion page.
Thank you!
[Kindle Highlights & Notes.pdf](https://github.com/yannick-cw/notionfy/files/5149387/Kindle.Highlights.Notes.pdf)
[last_output.txt](https://github.com/yannick-cw/notionfy/files/5149388/last_output.txt)

**Comment by yannick-cw** [comment]
@sgomezp for now you could try to rerun it a few times and see if it eventually synchs all highlights

**Comment by yannick-cw** [comment]
@sgomezp you could also send me your whole clippings file via email and I verify if it works here or what the problem is.

**Comment by sgomezp** [comment]
@yannick-cw 

Yes, sure! but please give me 1 hour, thanks!

**Comment by yannick-cw** [comment]
I see that you shared me the notion page, but can you share me your file directly from the kindle:
`kindlePath \ "documents" \ "My Clippings.txt`

**Comment by sgomezp** [comment]
Hi @yannick-cw 

I just forwarded to you the mail that I sent you 2 days ago with the "My Clippings.txt" file.
Please let me know if you receive it ok this time

Thank you!

**Comment by yannick-cw** [comment]
Thanks, this one arrived!

**Comment by yannick-cw** [comment]
Hey sorry for the long wait. It sync your file without any problem from my machine. I think it could be related to you internet connection or how notion handles your traffic. Did you try just syncing a few times to see if it gets all done eventually? Further syncs should be no problem
