### ISSUE TITLE
ParsErr

### ISSUE THREAD

**Issue by MariDantas** [yannick-cw/notionfy#16]
Hello, when I try to run the script, I receive the following error:

`ParsErr "(line 979, column 92):\nunexpected \"\\n\"\nexpecting \"\\r\\n\" or \"==========\\r\\n\""`

Do you know what this can be? I appreciate your help in advance.

**Comment by yannick-cw** [comment]
Hey, if you'd like you could send me your clippings file via email and I could investigate!
It is on your kindle -> `"documents" / "My Clippings.txt`

**Comment by yannick-cw** [comment]
Mhh this one is weird, I could synchronize you file without any problem, maybe you could try from a different computer?
(please wait for the 0.2.6 release thought, I am fixing something else, should be ready in a minute)

**Comment by MariDantas** [comment]
> Mhh this one is weird, I could synchronize you file without any problem, maybe you could try from a different computer?
> (please wait for the 0.2.6 release thought, I am fixing something else, should be ready in a minute)

Oh okay, let me know whenever the release is ready and I'll try it, okay?

**Comment by yannick-cw** [comment]
It is ready!
