### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by henkdevries1** [yannick-cw/notionfy#17]
Hi, 
installed Notionfy via Homebrew (version 2.6) and I get the error "syntax error near unexpected token `newline'" when I input the command with my cookie token, the page ID and the kinlde path. Any advise on what I should do differently?

Bram

**Comment by yannick-cw** [comment]
Hey, it seems to be an issue related to reading your snippings file, if you'd like you could email it to me. You find it in: 
`"documents" / "My Clippings.txt`
