### ISSUE TITLE
[Enhancement] Losing highlighted reference when taking notes

### ISSUE THREAD

**Issue by sergio-gimenez** [yannick-cw/notionfy#18]
First, thanks a lot @yannick-cw for this awesome tool, I use it very often within my reading workflow 😁.

Usually, while I read on my Kindle I take notes on the Kindle itself. I highlight the part of the text I want, and then I add a note on this text fragment. When I do that and then send it to Notion using `notionfy`, it syncs well, but it just keeps the note I wrote, losing the text fragment where the note belongs to. 

Let's see an example. From the `clippings.txt` file, a note I took looks something like 

```
﻿Factfulness (Hans Rosling)
- Your Highlight on page 135 | Location 2067-2071 | Added on Wednesday, August 5, 2020 10:02:43 PM

This is a note taken by me
==========
```

By looking at the `clippings.txt`, I'm not sure that it's so easy to extract the highlighted text. However, I think that might be easier to keep at least the reference, e.g: `Your Highlight on page 135 | Location 2067-2071 | Added on Wednesday, August 5, 2020 10:02:43 PM`. In Notion, it might look something like this:

![image](https://user-images.githubusercontent.com/42917235/106655706-00ef8c00-659a-11eb-8064-f2f59686a67e.png)

**Comment by yannick-cw** [comment]
Hey, sounds reasonable! I am happy that you like notionfy :)
I think I could add an option to include this information in the highlight. Just need to find some time to work on it. Thanks for the suggestion.

**Comment by yannick-cw** [comment]
Please check `0.3.0`, should add the reference now
https://github.com/yannick-cw/notionfy/releases/tag/0.3.0

**Comment by yannick-cw** [comment]
@sergio-gimenez hey, did that work for you? Would be great to get some feedback, as I took some of my free time just to get this feature done for you :)

**Comment by sergio-gimenez** [comment]
Hey @yannick-cw ! Sorry, busy week and I missed the notification. Thanks for the ping 😃.

I just tested it and works fine. Thanks for the enhancement
