### ISSUE TITLE
Possibility of utilizing this for the Kindle App?

### ISSUE THREAD

**Issue by anvimea** [yannick-cw/notionfy#5]
Hi,

I saw it mentioned that users who wished to see this feature - i.e., users who use the Kindle app on a phone, tablet, or Desktop, but not on the actual Kindle - should create an issue and see if it gains any traction.

Just throwing my hat into the ring! I'm not aware of the technical difficulties involved in importing cloud highlights, so if it's not possible I understand. Just saying there's an audience for it.

**Comment by yannick-cw** [comment]
Thanks for bringing that up! It is not a priority for me personally right now, as I am trying to make https://github.com/yannick-cw/notion-ocr easy to use as a service for everyone and integrating with with cloud highlights sounds like a lot of work and I have no clue yet how to it's possible. If there would be great demand for a it I might consider giving it more priority though ;)
Also pointers how to do that are appreciated

**Comment by hoodsy** [comment]
I read on the Kindle app as well and might take a stab at it!

This project is awesome - it might be handy to make a reading list based on your Kindle where you could see books your reading, progress, links to your highlights, and links to books you'd like to read

**Comment by yannick-cw** [comment]
Good idea! Please keep me updated if you try anything and need support.

**Comment by yannick-cw** [comment]
@hoodsy did you ever check feasibility of syncing from the apps?
