### ISSUE TITLE
notionfy: JSONError value not present

### ISSUE THREAD

**Issue by sbounmy** [yannick-cw/notionfy#8]
Hello,

I tried to run notionfy on macos today but had this error :

`notionfy: JSONError "Error in $.results[0]: parsing NotionClient.Results(Results) failed, key \"value\" not present"`

Did they change their API ?

**Comment by yannick-cw** [comment]
I can confirm the error, I guess it's the api, going to look into it, thanks for reporting!

**Comment by yannick-cw** [comment]
Can you check version `0.2.0`? That should fix it
