### ISSUE TITLE
deserializartion error - MacOS Catalina & Kindle

### ISSUE THREAD

**Issue by moccacoke** [yannick-cw/notionfy#9]
sttp.client.DeserializationError
notionfys.Notion$.$anonfun$getHighlights$3(Notion.scala:80)
scala.util.Either$LeftProjection.map(Either.scala:614)
notionfys.Notion$.$anonfun$getHighlights$2(Notion.scala:80)
cats.data.Kleisli.$anonfun$flatMap$2(Kleisli.scala:43)
cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.lang.Thread.run(Thread.java:834)
com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

**Comment by yannick-cw** [comment]
Hey, thanks for reporting! Are you trying to first time sync or has it worked before?
I am releasing a new version `2.0.2` which has a more verbose error logging if you run it with `--verbose`

Would be great if you can report the result of that. Just make sure to NOT include private information from the response body (e.g. email, full name)

**Comment by moccacoke** [comment]
Hi,

Good work!
It was my first attempt… anyway I managed to solve it by creating a new page in Notion, a blank one…the issue with the first Kindle Highlights page was that it was not empty, I added the toggle with your Setup in it and apparently that was the issue…you need a clean slate page just for the highlights otherwise you will receive the deserialization error…probably notionfy was trying to see if there are other highlights on the page so it not duplicate them (you said that notionfy knows how to check and copy the new highlights…). You got the idea, it got stuck when it found something different formated than one of the regular highlights and it got crashed… my opinion, is good to have it for maybe others that will commit the same mistake I did. Thank you for your workaround, it can be improved as for example summarize all the highlights from the same book in a separate page or table to have things more compact…otherwise is as good as you can get considering is an uniques and fast option to have all your offline highlights transferred…

V/R
mocca

**Comment by yannick-cw** [comment]
Great, #4 is about a different way of organizig the highlights, I am currently looking into that, it is not as trivial :)
